HomeWork add-friends-likes
SergeiNazarkin/java-filmorate pull request #3
Opened 2022-07-17 11:38 UTC by SergeiNazarkin

2022-07-17 17:57 UTC, Frilock requested changes
Пара небольших комментариев

2022-07-17 17:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> -@RequestMapping("/films")
А зачем убрали? Все равно же во всех методах этот префикс добавляете

2022-07-17 17:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void filmIdValidate(Integer filmId) {
По хорошему валидацию лучше тоже в отдельный класс вынести, назвать как нибуть FilmValidator или что то такое

2022-07-17 17:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public ErrorResponse(String error) {
Можете тоже убрать, повесив аннотацию AllArgsContructor

2022-07-17 17:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
У вас вроде специальный метод есть для такой проверки

2022-07-17 17:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Map<Integer, Film> getFilmsMap() {
А почему если метод публичный его в интерфейсе нет?

2022-07-18 16:30 UTC, SergeiNazarkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> -@RequestMapping("/films")
поправил

2022-07-18 16:32 UTC, SergeiNazarkin commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public ErrorResponse(String error) {
Добавил

2022-07-18 16:35 UTC, SergeiNazarkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
Точно) поправил.

2022-07-18 17:19 UTC, SergeiNazarkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void filmIdValidate(Integer filmId) {
Решил пока оставить , как есть.

2022-07-18 17:29 UTC, SergeiNazarkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void filmIdValidate(Integer filmId) {
А подскажите. получается мы создаем новый класс, пусть будет FilmValidator . он получается будет связан с контроллером через @Autowired? т.к. в валидации для проверки нужно запустить метод getUsersMap(). А в контроллере просто новый объект класса FilmValidator создаем?

2022-07-19 06:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void filmIdValidate(Integer filmId) {
Когда работаете с компонентами (банами) Spring, обычно новые объекты классов (если вы имеете ввиду через new) не создают. Вы помечаете свой FilmValidator аннотацией компонент, Spring его при старте создаст и поместит в свой контейнер. А в вашем контролере также через @Autowired вы "заинжектите" бин валидатора и выполните нужные проверки. Кстати валидацию тоже в сервисе лучше делать.
Надеюсь я правильно понял вопрос, если нет, то напишите в Slack

2022-07-19 06:33 UTC, Frilock approved these changes
Принято

2022-07-19 06:33 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +        log.info("404 {}", e.getMessage());
Я бы сделал данные логи более информативными =)

2022-07-20 06:47 UTC, merged